config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, presence: true
  validates :list_id, presence: true
  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %i[destroy]
  before_action :set_list, only: [:create]

  def create
    @bookmark = Bookmark.new(params_bookmark)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'lists/show'
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def params_bookmark
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render 'new'
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form_bookmark.html.erb
<%= simple_form_for([@list, @bookmark]) do |f| %>
  <div class="form-inputs">
    <%= f.association :movie %>
    <%= f.input :comment %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookmarks/delete.html.erb
<h1>Bookmarks#delete</h1>
<p>Find me in app/views/bookmarks/delete.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <%= link_to lists_path, class: "navbar-brand" do %>
        <%= image_tag "https://duetaz.org/wp-content/uploads/2018/07/Movie-Night.jpg" %>
        <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
           <%= link_to "My list", lists_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New List", new_list_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <br>
      <h1>My lists</h1>
      <ul class="list-group">
      <br>
        <% @lists.each do |list| %>
          <li class="list-group-item">
            <%= link_to list.name, list_path(list) %>
          </li>
        <% end %>
      </ul>
      <br>
      <br>
      <%= link_to "Add a new List", new_list_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<h1>Create a list</h1>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <%= simple_form_for @list do |f| %>
        <%= f.input :name %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="movie-container">

  <h2>
     <%= @list.name %>
  </h2>

  <div class="movies">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="carte">
          <div class="card-img">
            <img src="<%= bookmark.movie.poster_url %>" >
          </div>
          <div class="card-content">
            <%= bookmark.movie.title %>
            <%= bookmark.movie.overview %>
          </div>
        <div class="btn">
          <%= link_to '🗑️', bookmark_path(bookmark), method: :delete, data: { confirm: 'Are u sure ?' } %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="add-bookmark">
    <h3>Ajoute un bookmark</h3>
    <%= render 'bookmarks/form_bookmark', bookmark: @bookmark %>
    <%= link_to 'Retour', lists_path %>
  </div>


</div>